---
galaxy_info:
  author: Jorge Ricardo Vera
  description: Nginx como reverse proxy hacia la app Node.js, con TLS opcional
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - noble
  galaxy_tags:
    - nginx
dependencies: []
