---
galaxy_info:
  author: Jorge Ricardo Vera
  description: Certificado TLS de Let's Encrypt con Certbot y renovacion automatica
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - noble
  galaxy_tags:
    - tls
dependencies: []
